include:
  - project: "internal/integration/ci/pipelines/helm"
    ref: main
    file: "pipeline.yml"

helm-publish:
  variables:
    HELM_CHART_REGISTRY: ${CI_API_V4_URL}/projects/39/packages/helm/api/${CI_COMMIT_BRANCH}/charts

helm-docs:
  variables:
    DOCUMENT_DEPENDENCY_VALUES: "false"
  artifacts:
    paths:
      - "**/README.md"
    when: on_success
    expire_in: 1 days

push-readme:
  variables:
    FILES: "."
